package main

import (
	"log"
	"os"
	"path/filepath"
	"synrax/cli"

	"github.com/joho/godotenv"
)

func init() {
	log.SetFlags(log.LstdFlags | log.Lmicroseconds)

	localEnv, _ := filepath.Abs(".env")
	if _, err := os.Stat(localEnv); err == nil {
		_ = godotenv.Load(localEnv) // fallback in case of production failure
		log.Printf("main.init: loaded env file path=%s", localEnv)
	} else {
		log.Printf("main.init: env file not found path=%s", localEnv)
	}
}

func main() {
	log.Printf("main: starting CLI")
	/*
		Chain of operations:

		1) Start the CLI
		go run . read [id] [path] [oidc token]

		where:
		id - represents repository id
		path - is the path to the documentation utilized by the system to create report

		example command:
		go run . read 123 ./docs.txt

		2) `RunUnittest` will be ran which will:
			- Fetch the repo `configurations` for the database with the given repo_id
			- Fetch the test spec generated by the server (AI & other tooling) to test endpoints.

		3) With the given parameters, initialize `BuildReportFromDocumentation` that will run
		the unittest, and ultimately write the `report.json` at the root of this project.

		## TWO SERVERS MUST BE RUNNING ##
		- Tester server (such as python simple server) containing endpoints that match given docs.
		- Synrax server for AI tooling -> endpoint model + test spec generators.

		Now pray...
	*/
	cli.Execute()
}
